AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template for creating Lambdda"
Resources:
  MyRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: lambda-role
      AssumeRolePolicyDocument:
        Statement:
          - Action:
            - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
        FunctionName: 'lambda'
        Runtime: python3.6
        Code:
          ZipFile: |
            def handler(event, context):
              val = "${ValueToSub1}"
              print("This is a test with value '{}'.".format(val))
        Handler: index.handler
        MemorySize: 128
        Timeout: 10
        Role: !GetAtt MyRole.Arn
